steps:
# ユニットテストの実行
- name: 'python:3.11'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt', '-t', '.']

- name: 'python:3.11'
  entrypoint: python
  args: ['-m', 'pytest', '--junitxml=test-reports/junit.xml']
  
# Dockerイメージのビルド
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/news-collector:$SHORT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/news-collector:latest',
    '.'
  ]

# イメージのプッシュ
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/news-collector:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/news-collector:latest']

# Cloud Runへのデプロイ
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'news-collector'
  - '--image'
  - 'gcr.io/$PROJECT_ID/news-collector:$SHORT_SHA'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '1Gi'
  - '--timeout'
  - '3600'
  - '--set-env-vars'
  - 'ENVIRONMENT=production'
  - '--set-secrets'
  - 'SLACK_BOT_TOKEN=slack-bot-token:latest'
  - '--set-secrets'
  - 'SLACK_SIGNING_SECRET=slack-signing-secret:latest'

# Cloud Schedulerジョブの更新
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud scheduler jobs update http news-collector-job \
      --schedule="0 */3 * * *" \
      --uri="https://$REGION-run.googleapis.com/v1/projects/$PROJECT_ID/locations/$REGION/services/news-collector/run" \
      --http-method=GET \
      --attempt-deadline=3600s \
      --oidc-service-account-email=cloud-run-invoker@$PROJECT_ID.iam.gserviceaccount.com \
      --location=asia-northeast1

images:
- 'gcr.io/$PROJECT_ID/news-collector:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/news-collector:latest'

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY

tags: ['news-collector']

substitutions:
  _REGION: 'asia-northeast1'