# 企業一覧とスクレイピング設定
# HP・PRTimes URL などが定義されていましたが、HP関連を削除しPRTimesのみを残します

companies:
- id: "B23000199"
  name: "ALTURA X株式会社"
  # HPニュース設定 (hp_news) を削除
  prtimes:
    url: "https://prtimes.jp/main/html/searchrlp/company_id/57826"
    enabled: true

- id: "B24000278"
  name: "amu株式会社"
  # HPニュース設定 (hp_news) を削除
  prtimes:
    url: "https://prtimes.jp/main/html/searchrlp/company_id/102171"
    enabled: true

- id: "B23000182"
  name: "HelloWorld株式会社"
  # HPニュース設定 (hp_news) を削除
  prtimes:
    url: "https://prtimes.jp/main/html/searchrlp/company_id/68077"
    enabled: true

# スクレイピング共通設定
scraping:
  interval: 3600  # スクレイピング間隔(秒)
  timeout: 30     # リクエストタイムアウト(秒)
  retry: 3        # リトライ回数
  user_agent: "NewsBot/1.0"

# Slack通知設定
slack:
  channel: "#news-alerts"
  username: "News Bot"
  icon_emoji: ":newspaper:"
